version: "3.8"

services:
  # Servicio de la aplicación web en Node.js
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: clone_twitter_midu # Nombre del contenedor
    restart: always # Reiniciar siempre en caso de fallo
    working_dir: /app # Directorio de trabajo dentro del contenedor
    volumes:
      - ./:/app # Monta el directorio local "./app" dentro del contenedor en "/app"
      - $HOME/.ssh:/root/.ssh # Monta la carpeta ~/.ssh en el directorio /root/.ssh del contenedor
    ports:
      - "3000:3000" # Mapea el puerto 3000 del host al puerto 3000 del contenedor
